### ISSUE TITLE
Не видит пути при запуске через вирт. окружение venv\conda python.

### ISSUE THREAD

**Issue by NW15D** [Navatusein/Silero-TTS-Service#24]
Я уж и менял на абсолютные и так и эдак - не понимаю как он формирует путь или что не так с ошибкой.
Файлы в папке не создаются. 
(а если запускать без вирт окружения то  создаются, но кстати потом не чистятся, вроде должны ?)
А без вирт окружения - у остальных пакетов зависимости слетают.
Если подпаку audios удалить - приложение ее корректно создаст и создат там temp.wav

> INFO [2024-02-05 13:58:10] Time spent on the process: 3.8143470287323
INFO [2024-02-05 13:58:10] 192.168.0.44:33888 - "POST /process HTTP/1.1" 500
ERROR [2024-02-05 13:58:10] Exception in ASGI application
Traceback (most recent call last):
  File "/opt/conda/envs/silero/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/conda/envs/silero/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/opt/conda/envs/silero/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
    raise exc from None
  File "/opt/conda/envs/silero/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/opt/conda/envs/silero/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/conda/envs/silero/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/envs/silero/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/conda/envs/silero/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/conda/envs/silero/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/opt/conda/envs/silero/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/opt/conda/envs/silero/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/conda/envs/silero/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/conda/envs/silero/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/opt/conda/envs/silero/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/opt/conda/envs/silero/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/opt/conda/envs/silero/lib/python3.10/site-packages/starlette/responses.py", line 334, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path ./audios/xenia-5439322806554fc5d84099e7cd753769ad77b4c5d0dacd52939878066d5a9af2737659fd2a721bf764990c15aa377f43b472cbb8fe7f695243d1c6f376bd2d6e.wav does not exist.

**Comment by NW15D** [comment]
Ошибся, проблема исключительно в способе запуска - через systemd как сервис.
